# Generated by Django 4.2.4 on 2024-04-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_cartitem_cart_remove_cartitem_good_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
