# Generated by Django 4.2.4 on 2024-04-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_reservationtable_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableInRestourant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_num', models.IntegerField(max_length=100)),
            ],
        ),
    ]
