# Generated by Django 4.2.4 on 2024-04-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_tableinrestourant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationTable',
        ),
        migrations.DeleteModel(
            name='TableInRestourant',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default=55533, max_length=30),
            preserve_default=False,
        ),
    ]
