# Generated by Django 4.2.4 on 2024-04-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_tablereservation_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablereservation',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='first_name',
            field=models.CharField(default=55533, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='last_name',
            field=models.CharField(default=533111, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='phone_number',
            field=models.CharField(default=55533, max_length=20),
            preserve_default=False,
        ),
    ]
