# Generated by Django 4.2.4 on 2024-04-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_table_alter_tablereservation_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='table_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.table', to_field='name'),
        ),
    ]
